# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

import strawberry
from strawberry.schema_directives import Location


@strawberry.schema_directive(locations=[Location.FIELD_DEFINITION])
class Beta:
    pass
