# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

import strawberry
from strawberry import ID
from strawberry.scalars import *


@strawberry.type
class Test:
    booleanField: bool
    floatField: float
    idField: ID
    intField: int
    stringField: str
