# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from enum import Enum

import strawberry
from strawberry import ID
from strawberry.scalars import *


@strawberry.enum
class UserStatus(Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    PENDING = "PENDING"


@strawberry.type
class User:
    email: str
    id: ID
    name: str
    status: UserStatus


@strawberry.input
class CreateUserInput:
    email: str
    name: str
    status: UserStatus | None = UserStatus.ACTIVE
