# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

import strawberry
from strawberry.scalars import *


@strawberry.type
class Test:
    email: Email
    md5: MD5
