# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

import strawberry
from strawberry.scalars import *

from .custom.scalars import MD5, Email


@strawberry.type
class Test:
    email: Email
    md5: MD5
