# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from enum import Enum

import strawberry
from strawberry.schema_directives import Location


@strawberry.enum
class Status(Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


@strawberry.schema_directive(locations=[Location.FIELD_DEFINITION])
class Beta:
    pass


@strawberry.schema_directive(locations=[Location.FIELD_DEFINITION])
class Config:
    disabled: bool = False
    enabled: bool = True
    maxFloat: float = 3.14
    maxInt: int = 100
    message: str = 'Hello'
    minInt: int = 0
    name: str | None = None
    optionalInt: int | None = 42
    optionalString: str | None = 'default'
    required: bool
    required_with_default: bool = True
    status: Status = Status.ACTIVE


@strawberry.schema_directive(
    locations=[Location.FIELD_DEFINITION, Location.INPUT_FIELD_DEFINITION]
)
class Foo:
    bar: bool | None = None
    name: str | None = None
