# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Optional

import strawberry
from strawberry.schema_directives import Location


@strawberry.schema_directive(locations=[Location.FIELD_DEFINITION])
class Beta:
    pass


@strawberry.schema_directive(
    locations=[Location.FIELD_DEFINITION, Location.INPUT_FIELD_DEFINITION]
)
class Foo:
    bar: Optional[bool]
    name: Optional[str]
