# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from enum import Enum

import strawberry


@strawberry.enum
class Direction(Enum):
    ASC = "ASC"
    DESC = "DESC"
