# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from enum import Enum

import strawberry
from strawberry.scalars import *


@strawberry.enum
class Direction(Enum):
    ASC = "ASC"
    DESC = "DESC"


@strawberry.input
class PagingInput:
    from_: int | None = strawberry.field(name='from', default=0)
    limit: int = 100


@strawberry.input
class Sort:
    direction: Direction = Direction.ASC
