# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import List

import strawberry
from strawberry import ID
from strawberry.scalars import *


@strawberry.type
class User:
    id: ID
    optionalTags: List[str] | None
    tags: List[str]
