# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import List, Optional

import strawberry
from strawberry import ID
from strawberry.scalars import *


@strawberry.type
class User:
    id: ID
    optionalTags: Optional[List[Optional[str]]]
    tags: List[str]
