# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from typing import Optional

import strawberry
from strawberry import ID
from strawberry.scalars import *


@strawberry.type
class User:
    age: Optional[int]
    email: Optional[str]
    id: ID
    name: str
