# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

import strawberry
from strawberry import ID
from strawberry.scalars import *


@strawberry.type
class User:
    age: int | None
    email: str | None
    id: ID
    name: str
