# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

import strawberry
from strawberry.scalars import *


@strawberry.type
class Test:
    from_: int = strawberry.field(name='from')
    in_: str = strawberry.field(name='in')
    name: str


@strawberry.input
class TestInput:
    from_: int = strawberry.field(name='from')
    in_: str = strawberry.field(name='in')
    name: str
